apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-factory
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/itayherzberg/gitops-namespace-factory
      revision: HEAD
      files:
      - path: "tenants/*.yaml"

  template:
    metadata:
      name: '{{ namespace }}'  
    spec:
      project: default
      source:
        repoURL: https://github.com/itayherzberg/gitops-namespace-factory
        targetRevision: HEAD
        path: charts/namespace-factory
        helm:
          valueFiles:
          - '../../{ path.path }/{{ path.filename }}'

      destination:
        server: https://kubernetes.default.svc
        namespace: argocd

      syncPolicy:
        automated:
          prune: true
          selfHeal: true